# Generated by Django 3.1.4 on 2021-01-06 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0003_tamirci'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to', models.CharField(max_length=250)),
                ('frrom', models.CharField(max_length=250)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dukkanAdi', models.CharField(max_length=50)),
                ('il', models.CharField(max_length=50)),
                ('ilçe', models.CharField(max_length=50)),
                ('mahalle', models.CharField(max_length=50)),
                ('cadde', models.CharField(max_length=50)),
                ('sokak', models.CharField(max_length=50)),
                ('no', models.CharField(max_length=50)),
                ('tamirci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
