# Generated by Django 3.1.4 on 2021-01-06 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_map_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='extendedUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=10)),
                ('birthDay', models.DateField()),
            ],
        ),
    ]
