# Generated by Django 3.1.4 on 2021-01-16 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_extendedusers_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ariza1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sehir', models.CharField(max_length=30)),
                ('mahalle', models.CharField(max_length=30)),
                ('ariza', models.CharField(max_length=30)),
                ('tamirci', models.CharField(max_length=30)),
                ('arizadetay', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
